handoff_hosts:
    helpdesk_assistant:
      title: "Helpdesk Assistant"
      url: "http://52.188.160.175:5005"
    ## you can add more handoff hosts to this list e.g.
    # moodbot:
    #   title: "MoodBot"
    #   url: "http://localhost:5007"
    
